# Hyperparameter Sweep Configuration for WandB
# Use with: wandb sweep configs/sweep_config.yaml
# Then run: wandb agent <sweep_id>

program: train.py
method: grid
metric:
  name: eval/f1
  goal: maximize

parameters:
  training.learning_rate:
    values: [5.0e-5, 1.0e-4, 2.0e-4]
  training.batch_size:
    values: [16, 32, 64]
  training.weight_decay:
    values: [0.0, 0.01, 0.1]
  training.warmup_ratio:
    values: [0.0, 0.1]

# Early termination
early_terminate:
  type: hyperband
  min_iter: 3
